version: "3.3"
services:
  spark-master:
    image: $MYNAME/$IMAGE:$TAG
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "9000:9000"
      - "8088:8088"
      - "9870:9870"
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER_NODE=spark-master"
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/home/hadoop/sparkcmd.sh start"
  spark-worker:
    image: $MYNAME/$IMAGE:$TAG
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER_NODE=spark-master"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/home/hadoop/sparkcmd.sh start"
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default