version: "3.3"
services:
  spark-master:
    image: $MYNAME/$IMAGE:$TAG
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "9000:9000"
      - "8088:8088"
      - "9870:9870"
      - "22:22"
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_WEBUI_PORT=8080"
  spark-worker:
    image: $MYNAME/$IMAGE:$TAG
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - 8080
      - 22
    networks:
      - spark-network
    environment:
      - "SPARK_WORKER_WEBUI_PORT=8080"
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default